### PR TITLE
#27 - Add createBucket method & tests

### PR DESCRIPTION
**Pull request by neilstuartcraig**

### CODE REVIEW

**Comment by neilstuartcraig** [comment]
Hi @MathieuLoutre - I squashed and force pushed my branch, also bumped the minor version to 2.3.0 to reflect the added feature. Hope that's all OK.

**Comment by neilstuartcraig** [comment]
Sorry, had to fix an issue and re-squash

**Comment by MathieuLoutre** [comment]
Looks great! Much easier to read that way ;)
Thanks again for the hard work.

**Comment by neilstuartcraig** [comment]
Great. It's worked well for my use case but happy to fix its or improve it if needed. 
Cheers

**Pull request merged**
