### PR TITLE
Return an object containing the send method

### LINKED ISSUE #23: putObject should return an object
https://github.com/MathieuLoutre/mock-aws-s3/blob/4b247d682b6879d6b9da45b859886a84502fa54f/lib/mock.js#L221-L255

Me and @AllieRays coded  a solution to return an object containing the `send` method, simulating the s3 module. :four_leaf_clover: 

@AllieRays Don't forget to fork, commit, pull request that change, so after `npm install`ing you will not lose it. :joy:

### PR DESCRIPTION
**Pull request by IonicaBizau**
Fixed #23  :joy: 

/cc @AllieRays

### CODE REVIEW

**Comment by MathieuLoutre** [comment]
Any chance on writing a quick test? This looks good but it'd be best with a short test if you can.

**Comment by IonicaBizau** [comment]
@MathieuLoutre Done :grin:

**Comment by MathieuLoutre** [comment]
Awesome!

**Comment by IonicaBizau** [comment]
:tada:

**Comment by MathieuLoutre** [comment]
Published in `2.1.0`! Thank you :)

**Comment by IonicaBizau** [comment]
Amazing! :+1: :tada:

**Pull request merged**
