### PR TITLE
Updated example to use bound parameters

### PR DESCRIPTION
**Pull request by CJNE**
The default options needs to be wrapped in params now

### CODE REVIEW

**Comment by MathieuLoutre** [comment]
Hi! Sorry, I gathered from the PR that this was backwards compatible. Is it not?
If not, I will update the version so it's `2.0.0`.

**Comment by CJNE** [comment]
Hi! I'm sorry that i wasn't clearer on that, it is *not* backwards compatible. 
It would be easy to make it so but maybe that will be confusing?
Let me know if you want any help on it!

**Comment by MathieuLoutre** [comment]
Strange. The way I use the SDK, I can pass the bucket without going through a `params` object, just using a top level object. I'm wondering if I've been doing something wrong all that time... If not, there's probably a case to make it backwards compatible.

**Comment by CJNE** [comment]
Not sure why that has worked for you.. bound parameters were introduced in v0.9.8-pre.9 (2013).
There are some things you can pass in the top level object, such as region. 
This is called service specific configuration:
http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-services.html

You *should* get an error if you try to do a request that requires a bucket if you don't have it in the service call params (or bound params).

**Comment by MathieuLoutre** [comment]
Here's some code that's working:

```js
var s3_options = {
	bucket: options.bucket,
	accessKeyId: options.accessKeyId,
	secretAccessKey: options.secretAccessKey,
	sessionToken: options.sessionToken
};

var s3 = new AWS.S3(s3_options);
```

As I understand, this wouldn't work with the current code, however it seems to be a valid use of the SDK (`2.0.x`). Does that trigger an error for you?

**Comment by CJNE** [comment]
Hi,

I just did a test with this:

var AWS = require('aws-sdk');
var options = {
  bucket: 'tsrsubmissions',
  accessKeyId: '1234',
  secretAccessKey: '3476',
  sessionToken: 'sometoken'
};
var s3 = new AWS.S3(options);
var params = {
  Prefix: '/'
}
s3.listObjects(params, function(err, data) {
  if(err) console.log(err, err.stack);
  else console.log(data);
});

errors with:

{ [MissingRequiredParameter: Missing required key 'Bucket' in params]
  message: 'Missing required key \'Bucket\' in params',
  code: 'MissingRequiredParameter',
  time: Mon Nov 02 2015 09:10:28 GMT+0100 (CET) }


(using Bucket (capital B) for key gives the same error)

It doesn't error until you actually try to perform an action though, so
your example does not give an error since you don't do anything with s3 in
it.
This is aws-sdk version 2.1.14


/Johan


2015-11-01 23:39 GMT+01:00 Mathieu Triay <notifications@github.com>:

**Comment by MathieuLoutre** [comment]
Thanks for looking into it @CJNE! I think it's a weird case. Since I always included `bucket` in my arguments, I've never had a problem (obviously, all other attributes are unused by the mock library so it wasn't a problem there either).

I think, just to be on the safe side, I'll delete the latest version and republish it as `1.0.0` to mark the possible (but unlikely) breaking change. Does that seem fair?

**Comment by CJNE** [comment]
Yeah that's probably a good thing to do as it might break peoples tests :)

**Comment by MathieuLoutre** [comment]
Published `2.0.0` for a clean slate. Thanks again for your help!

**Pull request merged**
