### PR TITLE
fixed .promise() methods for all APIs

### PR DESCRIPTION
**Pull request by viral-sh**
### Currently, `.promise()` method only works for `.upload(...)` method and fails for all others.

The assumption  for `createPromisable()` method was that each API will have 3 arguments: search, options, callback. However, this is not true for most APIs, which have only 2 argument

## Change
1. Now instead we look at the actual last argument passed (Provided arguments.length is between `[2, wrappedFunc.length]`). This ensures that promise wrapper works for all APIs
2. Current `package-lock.json` has an issue which fails `npm run install`. Hence, recreated it.

This PR fixes issue #50

### CODE REVIEW

**Comment by viral-sh** [comment]
Current tests are passing but Need Help to add more tests regarding `.promise()` methods

**Comment by viral-sh** [comment]
@MathieuLoutre Are you still maintaining this?

**Comment by MathieuLoutre** [comment]
I don’t have a lot of time to look into this at the moment unfortunately. I was looking for an additional maintainer a few months ago but no luck. If anyone fancies, let me know. Otherwise I’ll take a look at these PR when I get the time.

**Comment by pal** [comment]
This fix really helped me out, please merge I you get the chance, or invite @viral-sh as contributor

Thanks @viral-sh!

**Comment by djemalmohamed** [comment]
Could you please merge this PR

**Comment by MathieuLoutre** [comment]
Merged in v4

**Pull request merged**
