### PR TITLE
Match upload api

### PR DESCRIPTION
**Pull request by kyleseely**
There is an optional `options` parameter in the upload function.

### CODE REVIEW

**Comment by MathieuLoutre** [comment]
Seems good. Do you have the link to the doc/code that shows this behaviour?
(Sorry for the delay, for some reason I didn't get an email...)

**Comment by kyleseely** [comment]
Here's the docs: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property

and the code: https://github.com/aws/aws-sdk-js/blob/11383198a48c8fe7a3d1d7dcbeedfc74ce73ce5e/lib/services/s3.js#L441

**Comment by MathieuLoutre** [comment]
Awesome! Just wanted to have a record somewhere before merging (as it's not even a breaking change).

**Comment by MathieuLoutre** [comment]
Published in `2.0.0`. Thank you!

**Pull request merged**
